---
title: Louie The Dog
short_title: Lou
description: A Day at Work
baseurl: 
permalink: "/:path/"
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
jekyll-archives:
  enabled: all
  layout: archive
gems:
- jekyll-menus
- jekyll-feed
- jekyll-archives
