---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Editions
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Subscription Content
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Subscription Packages
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Cartoons
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Posts
  create: all
  match: "**/*"
upload_dir: uploads
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: jekyll build
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
version: '0.53'
