---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Other
- type: directory
  path: content/people
  label: Authors
  create: all
  match: "**/*"
- type: document
  path: data/publications.yaml
  label: Landing Pages
  match: "**/*"
- type: directory
  path: content
  label: Editions
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Cartoons
  create: all
  match: "**/*"
  exclude: content/projects/_index.md
- type: directory
  path: content/projects
  label: 'Blogs '
  create: all
  match: "**/*"
  exclude: content/projects/_index.md
- type: directory
  path: ''
  label: Posts
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: jekyll build
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
